[package]
name = "fisika"
description = "A physics library"
version = "0.1.0"
edition = "2018"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
license = "MIT/Apache-2.0"
include = [
    "src/**/*.rs",
    "Cargo.toml",
	"LICENSE-*",
]
publish = false

[dependencies]
glam = "0.17.*"
paste = "1.0.5"
# pretty_dtoa = "0.3.0"
# num = "0.4.0"

[dev-dependencies]
float_eq = "0.6.0"
macroquad = "0.3.8"

# related crates:
#
# uom = "0.31.1"
# mag = "0.3.0"
# physical_constants = "0.4.1"
# rapier2d = "0.8.0"
# rapier3d = "0.8.0"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./src/docs-header.html" ]
