[alias]

# BUILD
b = "build"
br = "build --release"

# RUN
r = "run"
rr = "run --release"
re = "run --example"
rb = "run --bin"

# DOC
d = "doc --no-deps"
do = "doc --no-deps --open"

# TEST
t = "test -- --nocapture"

[build]
rustdocflags = [ "--html-in-header", "./src/docs-header.html"]
